### ISSUE TITLE
Add support for Data-star and AlpineJS

### ISSUE THREAD

**Issue by BKFlister** [thomasborgen/hypermedia#19]
Hi,
Just found Hypermedia in my search for using python directly instead of jinja2 for creating html.

I am testing using it with the Datastar module https://data-star.dev. Also just recently discovered.
Datastar uses `data-*`, like `data-show`, `data-text`, `data-model`, `data-on-click`, `data-bind-disabled`,...
This is currently not supported by Hypermedia.
In addition Datastar uses `.duration` or `.duration_500ms` as modifiers, for example like `data-show.duration_500ms` for animation.

I found that in models.py, after line 102, I could add the following code to get it working.
Using the same `key.replace("_", "-")` as for htmx: `hx-`, and added a check for `_duration`
```python
data_keys = [key for key in attributes.keys() if key.startswith("data_")]
for key in data_keys:
    if "_duration" in key:
        new_key = key.replace("_", "-", 1).replace("_duration", ".duration")
    else:
        new_key = key.replace("_", "-")
    attributes[new_key] = attributes.pop(key)
```
This code is not future proof.

In addidion AlpineJS, a module that is often used together with htmx.
AlpineJS uses `x-*`, like `x-show`, `x-text`, `x-transition` ..., 
and use modifiers like `x-transition.duration.500ms` and `x-transition:enter.scale.80`
(I must admit that I have not tested AlpineJS with Hypermedia yet.)

Can use of a dict for attributes having modifiers be an option?
For example:
attributes={'data-show.duration_500ms':'$show'} (datastar)
attributes={'x-transition.duration.500ms':'$show'} (alpinejs)
if modifiers is not used, the normal `data_show='$show'` should be used

Maybe you will find a better and more future proof method.

I made a quick test/example using the python backend example from the data-star page.
https://gist.github.com/BKFlister/7dfe85d3b3c44598703bb20c27a7f218
I used your williott code as an example to get my test working.
Had to use `.dump()` as htmx is not used.
Is there a better method to return the page?

Thank You
BR
Bjorn-Kare

**Comment by thomasborgen** [comment]
Thanks for taking an interest in Hypermedia and opening an issue!

Yes, the simple and short answer is that you can do something like this:

```python
Div(**{"x-transition.duration_500ms": "my"}
```

Just tried adding this and this passes:

```python
def test_custom_attributes() -> None:
    element = TestElement(**{"data-show.duration_500ms": "$show"})
    assert element._render_attributes() == " data-show.duration_500ms='$show'"
```

> Spreading a dict makes them act like keyword arguments without python syntax limiting the keyword string.

The long answer I'll get back to tonight after dinner->family-time->putting kids to bed :)

**Comment by thomasborgen** [comment]
Hi again.

The biggest problem with this is basically python. We cannot use `.`, `-`, `:`, `@` or other symbols in keyword arguments.

The simple way around this is to spread a dictionary to the constructor like I meantioned above:

```python
Div(**{"x-transition.duration_500ms": "$show"}
# <div x-transition.duration_500ms='$show'></div>

Button(**{"@click": "open = ! open"})
# <button @click='open'></button>
```

Another solution to the problem would be to for example let `.` being represented by something else like double underscores. But to what end? theres `@` and `:` and probably many other symbols that are used by various js frameworks. So I don't like this idea. 

My goal with this library is to make it feel as close as possible to writing normal html as we can. Because of that, for now `spreading a dict` seems like the best way that does not force a hypermedia user to learn something different.

We do however need to document this!


> @BKFlister  I made a quick test/example using the python backend example from the data-star page.
https://gist.github.com/BKFlister/7dfe85d3b3c44598703bb20c27a7f218
I used your williott code as an example to get my test working.
Had to use .dump() as htmx is not used.
Is there a better method to return the page?

Super cool to see someone try out Hypermedia 😊 

`.dump()` is the correct way to produce the html from the model. I wouldn't mind adding a `.to_html()` method as well if you think that is clearer for the user.

**Comment by BKFlister** [comment]
Thank you, 
`Spreading as dict` works nicely, and it will also support other variants of attributes.
And not having to add `.replace("_", "-")` for all types, hx-* x-*, data-* , whatevernext-*

`.dump()` is ok, but `.to_html` might be clearer for new users.

I see that you have updated the README.MD, one correction for Datastar:
# Datastar
Div(**{"data-show.duration_500ms":"$show"}).dump()
# <div data-show.duration_500ms='$show'></div>


For AlpineJS
Div(**{x-show="open", "x-transition.duration_500ms"}).dump()
# <div x-show="open" x-transition.duration.500ms></div>
For AlpineJS and `x-transition.duration_500ms` one might need `:true`  to get it working, as it does not bind to a value?
`Div(**{x-show="open", "x-transition.duration_500ms":true}).dump()`  ?
https://alpinejs.dev/directives/transition

I will see if I can do a test later.

**Comment by thomasborgen** [comment]
Awesome!

Here is a PR for the alpine and datastar doc changes. https://github.com/thomasborgen/hypermedia/pull/24
It would help a lot if you could test if it works locally for you and give me a thumbs up if it works or a correction if it doesn't. 

If this issue is done you can close this. If there is anything else just let me know either here or in a new issue.

**Comment by BKFlister** [comment]
Did a small test with AlpineJS
`"x-transition.duration_500ms"` must be set to true:  `"x-transition.duration_500ms":True`
The correct example will be:

```
# Alpine.js
Div(**{x-show="open", "x-transition.duration_500ms:True"}).dump()
# <div x-show="open" x-transition.duration.500ms></div>
```


For the `x-data`, that contains a dict of values, I have to use `json-dumps()`.
Example:
```python
Div(
  Button("Toggle", **{"@click":"show=!show;console.log(show)"}),
  Div(id="output", **{"x-text":"output"}),
  Div(
    Span("Element to toogle"),
    Span(id="feed"),
    **{"x-show":"show","x-transition.duration.500ms":True}
  ),
  **{"x-data":json.dumps({"show":True, "output":"Test of x-text"})}
)
```

**Comment by thomasborgen** [comment]
Updated the docs with some general comments about how we generate the attribute names now. 

All html attributes now are typed and have autocompletion and defined aliases for output names.
Those who dont we will change all underscores to dashes. This is very useful for htmx.
Then if you want to keep underscores  prefix your key string with a `$` and nothing will change it (except that we remove that prefix).

Your example above should now work like this. 

```python
Div(
  Button("Toggle", **{"@click":"show=!show;console.log(show)"}),
  Div(id="output", x_text="output"),
  Div(
    Span("Element to toogle"),
    Span(id="feed"),
    x_show="show",
    **{"x-transition.duration.500ms":True}
  ),
  x_data='{"show": True, "output": "Test of x-text"}'
  # or: 
  x_data=json.dumps({"show":True, "output":"Test of x-text"})
)
```

**Comment by BKFlister** [comment]
This can be closed as solved.
Tested datastar and alpine with v.5.1.0
ref:
`2. Any attribute that is prefixed with $ will be outputted as is without the first $.`

Thank you
